[package]
name = "website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
emojicons = "1.0.1"
handlebars = "4.3.6"
pulldown-cmark = "0.9.2"
toml = "0.7.3"
walkdir = "2.3.3"
